### ISSUE TITLE
Add potential protocols

### ISSUE THREAD

**Issue by Quackdoc** [probonopd/wayland-x11-compat-protocols#14]
ScreenCapture;
Maybe not the greatest well fleshed out thing in the world, but `ext-screencopy-v1` will (at least partially) address this
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/124

Process info;
only partially but `ext-foreign-toplevel-list` (Merged) and `Add foreign-toplevel-state` (PR) which is a subset of `wlr-foreign-toplevel-management` may provide some help

**Comment by probonopd** [comment]
Hi [Quackdoc](https://github.com/Quackdoc), thanks for your comment. Would you like to make the necessary edits to README.md and send a pull request?
